export type AppLanguage = "en" | "km"

const messages = {
  en: {
    common: {
      stockflow    : "StockFlow",
      inventory    : "Inventory",
      management   : "Management",
      orContinue   : "Or continue",
      terms        : "Terms",
      privacyPolicy: "Privacy Policy",
      signOut      : "Sign Out",
    },
    auth: {
      adminConsole       : "Admin Console",
      signIn             : "Sign in",
      accessSecurely     : "Access your dashboard securely.",
      email              : "Email",
      password           : "Password",
      rememberMe         : "Remember me",
      days30             : "30 days",
      use8Chars          : "Use at least 8 characters.",
      tooShort           : "Too short - add more characters.",
      looksGood          : "Looks good.",
      welcomeBack        : "Welcome back. Redirecting...",
      invalidCredentials : "Invalid credentials. Please try again.",
      signingIn          : "Signing in...",
      signInWithSso      : "Sign in with SSO",
      createAccount      : "Create account",
      createAdminAccount : "Create an admin account with your personal details.",
      fullName           : "Full Name",
      jobTitle           : "Job Title",
      phone              : "Phone",
      bio                : "Bio",
      profileImage       : "Profile Image",
      uploadPhoto        : "Upload photo",
      switchToRegister   : "Need an account? Register",
      switchToSignIn     : "Already have an account? Sign in",
      registering        : "Creating account...",
      registrationSuccess: "Account created. Redirecting...",
      invalidImage       : "Please choose a valid image file.",
      agreePrefix        : "By continuing, you agree to our",
      and                : "and",
      secureAdminAccess  : "Secure admin access",
    },
    sidebar: {
      overview     : "Overview",
      products     : "Products",
      inventory    : "Inventory",
      purchases    : "Purchases",
      sales        : "Sales",
      reports      : "Reports",
      users        : "Users",
      settings     : "Settings",
      administrator: "Administrator",
    },
    header: {
      searchPlaceholder: "Search products, SKU, invoices...",
      thisWeek         : "This week",
      thisMonth        : "This month",
    },
    dashboard: {
      salesVsPurchases   : "Sales vs Purchases",
      weeklyComparison   : "Weekly analytical comparison",
      sales              : "Sales",
      purchases          : "Purchases",
      stockByCategory    : "Stock by Category",
      distribution       : "Distribution of products",
      units              : "Units",
      recentTransactions : "Recent Transactions",
      viewAll            : "View all",
      type               : "Type",
      reference          : "Reference",
      amount             : "Amount",
      date               : "Date",
      status             : "Status",
      lowStockProducts   : "Low Stock Products",
      requiresAttention  : "Requires immediate attention",
      reorder            : "Reorder",
      manageAlerts       : "Manage Alerts",
      totalSalesToday    : "Total Sales (Today)",
      totalPurchasesToday: "Total Purchases (Today)",
      netProfitToday     : "Net Profit (Today)",
      lowStockAlerts     : "Low Stock Alerts",
      vsYesterday        : "vs yesterday",
      since8am           : "since 8AM",
    },
    settings: {
      title              : "Settings",
      description        : "Configure your application preferences.",
      lightMode          : "Light Mode",
      lightDescription   : "Bright surfaces with high contrast for daytime work.",
      darkMode           : "Dark Mode",
      darkDescription    : "Low-glare surfaces with softer contrast for late hours.",
      quickToggle        : "Quick Toggle",
      currentTheme       : "Current theme",
      switchToLight      : "Switch to Light Mode",
      switchToDark       : "Switch to Dark Mode",
      profileTitle       : "Admin Profile",
      profileDescription : "Manage your personal information and profile image.",
      accountEmail       : "Account email",
      roleLabel          : "Role",
      saveProfile        : "Save profile",
      savingProfile      : "Saving...",
      profileSaved       : "Profile updated successfully.",
      language           : "Language",
      languageDescription: "Choose the language used in the interface.",
      english            : "English",
      khmer              : "Khmer",
      currentLanguage    : "Current language",
    },
  },
  km: {
    common: {
      stockflow    : "StockFlow",
      inventory    : "ស្តុក",
      management   : "ការគ្រប់គ្រង",
      orContinue   : "ឬបន្ត",
      terms        : "លក្ខខណ្ឌ",
      privacyPolicy: "គោលការណ៍ឯកជនភាព",
      signOut      : "ចាកចេញ",
    },
    auth: {
      adminConsole       : "ផ្ទាំងគ្រប់គ្រងអ្នកគ្រប់គ្រង",
      signIn             : "ចូលប្រើ",
      accessSecurely     : "ចូលទៅកាន់ផ្ទាំងគ្រប់គ្រងរបស់អ្នកដោយសុវត្ថិភាព។",
      email              : "អ៊ីមែល",
      password           : "ពាក្យសម្ងាត់",
      rememberMe         : "ចងចាំខ្ញុំ",
      days30             : "30 ថ្ងៃ",
      use8Chars          : "ប្រើយ៉ាងហោចណាស់ 8 តួអក្សរ។",
      tooShort           : "ខ្លីពេក - បន្ថែមតួអក្សរទៀត។",
      looksGood          : "មើលទៅល្អ។",
      welcomeBack        : "ស្វាគមន៍ការត្រឡប់មកវិញ។ កំពុងបញ្ជូនបន្ត...",
      invalidCredentials : "អ៊ីមែល ឬ ពាក្យសម្ងាត់ មិនត្រឹមត្រូវ។",
      signingIn          : "កំពុងចូល...",
      signInWithSso      : "ចូលជាមួយ SSO",
      createAccount      : "បង្កើតគណនី",
      createAdminAccount : "បង្កើតគណនីអ្នកគ្រប់គ្រងជាមួយព័ត៌មានផ្ទាល់ខ្លួនរបស់អ្នក។",
      fullName           : "ឈ្មោះពេញ",
      jobTitle           : "តួនាទីការងារ",
      phone              : "លេខទូរស័ព្ទ",
      bio                : "ប្រវត្តិខ្លី",
      profileImage       : "រូបភាពប្រវត្តិរូប",
      uploadPhoto        : "បញ្ចូលរូបភាព",
      switchToRegister   : "មិនទាន់មានគណនី? ចុះឈ្មោះ",
      switchToSignIn     : "មានគណនីរួចហើយ? ចូលប្រើ",
      registering        : "កំពុងបង្កើតគណនី...",
      registrationSuccess: "បានបង្កើតគណនី។ កំពុងបញ្ជូនបន្ត...",
      invalidImage       : "សូមជ្រើសរើសឯកសាររូបភាពត្រឹមត្រូវ។",
      agreePrefix        : "ដោយបន្ត អ្នកយល់ព្រមនឹង",
      and                : "និង",
      secureAdminAccess  : "ការចូលប្រើអ្នកគ្រប់គ្រងដោយសុវត្ថិភាព",
    },
    sidebar: {
      overview     : "ទិដ្ឋភាពទូទៅ",
      products     : "ផលិតផល",
      inventory    : "ស្តុក",
      purchases    : "ការទិញ",
      sales        : "ការលក់",
      reports      : "របាយការណ៍",
      users        : "អ្នកប្រើប្រាស់",
      settings     : "ការកំណត់",
      administrator: "អ្នកគ្រប់គ្រង",
    },
    header: {
      searchPlaceholder: "ស្វែងរកផលិតផល, SKU, វិក្កយបត្រ...",
      thisWeek         : "សប្តាហ៍នេះ",
      thisMonth        : "ខែនេះ",
    },
    dashboard: {
      salesVsPurchases   : "ការលក់ និង ការទិញ",
      weeklyComparison   : "ការប្រៀបធៀបវិភាគប្រចាំសប្តាហ៍",
      sales              : "ការលក់",
      purchases          : "ការទិញ",
      stockByCategory    : "ស្តុកតាមប្រភេទ",
      distribution       : "ការចែកចាយផលិតផល",
      units              : "ឯកតា",
      recentTransactions : "ប្រតិបត្តិការថ្មីៗ",
      viewAll            : "មើលទាំងអស់",
      type               : "ប្រភេទ",
      reference          : "លេខយោង",
      amount             : "ចំនួន",
      date               : "កាលបរិច្ឆេទ",
      status             : "ស្ថានភាព",
      lowStockProducts   : "ផលិតផលស្តុកទាប",
      requiresAttention  : "ត្រូវការការយកចិត្តទុកដាក់ភ្លាមៗ",
      reorder            : "បញ្ជាទិញឡើងវិញ",
      manageAlerts       : "គ្រប់គ្រងការជូនដំណឹង",
      totalSalesToday    : "ការលក់សរុប (ថ្ងៃនេះ)",
      totalPurchasesToday: "ការទិញសរុប (ថ្ងៃនេះ)",
      netProfitToday     : "ប្រាក់ចំណេញសុទ្ធ (ថ្ងៃនេះ)",
      lowStockAlerts     : "ការជូនដំណឹងស្តុកទាប",
      vsYesterday        : "ប្រៀបនឹងម្សិលមិញ",
      since8am           : "ចាប់ពីម៉ោង 8 ព្រឹក",
    },
    settings: {
      title              : "ការកំណត់",
      description        : "កំណត់ចំណូលចិត្តកម្មវិធីរបស់អ្នក។",
      lightMode          : "របៀបភ្លឺ",
      lightDescription   : "ផ្ទៃភ្លឺ និង ច្បាស់សម្រាប់ការងារពេលថ្ងៃ។",
      darkMode           : "របៀបងងឹត",
      darkDescription    : "ផ្ទៃមិនចាំងភ្នែក សម្រាប់ការងារពេលយប់។",
      quickToggle        : "ប្តូររហ័ស",
      currentTheme       : "របៀបបច្ចុប្បន្ន",
      switchToLight      : "ប្តូរទៅរបៀបភ្លឺ",
      switchToDark       : "ប្តូរទៅរបៀបងងឹត",
      profileTitle       : "ប្រវត្តិរូបអ្នកគ្រប់គ្រង",
      profileDescription : "គ្រប់គ្រងព័ត៌មានផ្ទាល់ខ្លួន និង រូបភាពប្រវត្តិរូបរបស់អ្នក។",
      accountEmail       : "អ៊ីមែលគណនី",
      roleLabel          : "តួនាទី",
      saveProfile        : "រក្សាទុក",
      savingProfile      : "កំពុងរក្សាទុក...",
      profileSaved       : "បានធ្វើបច្ចុប្បន្នភាពប្រវត្តិរូបរួចរាល់។",
      language           : "ភាសា",
      languageDescription: "ជ្រើសរើសភាសាសម្រាប់បង្ហាញក្នុងប្រព័ន្ធ។",
      english            : "អង់គ្លេស",
      khmer              : "ខ្មែរ",
      currentLanguage    : "ភាសាបច្ចុប្បន្ន",
    },
  },
} as const

const getMessage = (language: AppLanguage, path: string) => {
  const segments = path.split(".")
  let current: any = messages[language]

  for (const segment of segments) {
    current = current?.[segment]
  }

  return typeof current === "string" ? current : path
}

export const useAppLanguage = () => {
  const language = useCookie<AppLanguage>("app_language", {
    default: () => "en",
    path: "/",
    sameSite: "lax",
  })

  const setLanguage = (value: AppLanguage) => {
    language.value = value
  }

  const t = (path: string) => getMessage(language.value, path)

  const isKhmer = computed(() => language.value === "km")

  return {
    language,
    isKhmer,
    setLanguage,
    t,
  }
}
